### ISSUE TITLE
Update Mailchimp API to Account for Offset Numbers

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#163] opened 2016-07-21 20:11 UTC
_TASK_
-------------------
#### Request
Update the mailchimp subscribe API to account for offset numbers (if we receive 10,000+ subscriptions within two hours). 

#### Additional Information

- relevant campaign NIDs, run NIDs, dates, etc.

#### Why This Matters/Use Case Example
This could be the reason why our UI and API member counts do not match up -- see https://github.com/DoSomething/quasar/issues/141

**Comment by jessleenyc** [comment] 2016-07-25 16:30
Relates to https://github.com/DoSomething/quasar/issues/141

**Comment by sheyd** [comment] 2016-08-18 14:17
Can confirm that we do have time slices with over 10000 members, based on some test code I generated and logged yesterday scraping the MailChimp API. Working on confirming ETL logic before testing on daily subscribe/unsubscribe scripts.

**Comment by sheyd** [comment] 2016-08-22 13:49
Good news, looks like member count going up is working. Bad news, the server ran out of RAM while it was running so have to up the server instance size for more juice. Doing that shortly.

**Comment by sheyd** [comment] 2016-08-25 14:22
Should have put this in here first:

My last 3 re-factoring attempts haven't worked. I'm going to try 2 very straightforward attempts to improve this:

Up the number of record gets from 10000 to 20000
Move the time slice from 2 hours down to 1 hour (or lower).
It's a priority to get this out, and this is the lowest/easiest barrier way to test out our count disparity without too much code re-factoring.

**Comment by sheyd** [comment] 2016-08-25 14:24
Adding some contextual details of what I tried:

1. My initial attempt was adding loop logic to set `offset` param for MailChimp API in a `while` loop, and iterate if returned member array count if it was > 10000. Unfortunately, I wasn't incrementing the `offset` variable correctly, and it was stuck in an infinite loop. 👎

**Comment by sheyd** [comment] 2016-08-25 16:38
@jessleenyc @nmccormick619 @Bladt Better news! From the test query, the new count total is only off by ~52K. so the first pass of increasing number of records to 20000 per time interval, we've closed the gap. I'm going to try 30000 records.

**Comment by sheyd** [comment] 2016-08-29 14:55
Tried using all the way down to every 10 minutes with 20000 records, but it takes about 15 hours to run. The happy compromise we're putting into prod for now is 25000 records every 30 minutes.

**Comment by sheyd** [comment] 2016-08-29 20:54
One final note that we can address when I get back is to instead of using iterative timeblocks, set origin time period and end time period to when script runs, and then use a combination of count and offset to paginate off a static time period. 

i.e. start time: 1/1/2010, end-time: 8/29/2016, count = 10000, offset=0 -> 
start time: 1/1/2010, end-time: 8/29/2016, count = 10000, offset=10000 ->
start time: 1/1/2010, end-time: 8/29/2016, count = 10000, offset=20000

I tested it in Paw on the unsubscribe endpoint, and even with an offset of 1000000, it returns a coherent result set. What this means is we can iterate till we have 0 records returned, and it's then the end of the member set. cc @DFurnes @mshmsh5000 Let's explore next sprint when I get back.

**Comment by sheyd** [comment] 2016-08-30 16:58
Temporarily reverted to 20000 subscribers/hour time slicing since other more intense query metrics cause timeouts.

**Comment by sheyd** [comment] 2016-09-23 19:26
https://github.com/DoSomething/etl-scripts/pull/71 for this issue (via subscribers). Once tested will update unsubscribers script as well.

**Comment by sheyd** [comment] 2016-09-26 17:39
Current state is the improved pagination paradigm is we're closing in on the final numbers in MailChimp, but job is running longer and occasionally failing. Tweaking pagination numbers to try compensating.

**Comment by nmccormick619** [comment] 2016-09-26 18:21
select *
from mobile_user_lookup mul
left join mobile_users mu on mul.phone_number=mu.phone_number
left join mailchimp_unsub muns on muns.email_address=mu.email
left join mailchimp_sub msub on msub.email_address=mu.email
where mul.uid IS NOT NULL
and mu.status='Active Subscriber'
and muns.unsub_time IS NOT NULL
and muns.unsub_time>msub.confirm_time

^ Check with someone (Andrea?) to know if mobile user table has accurate emails.

**Comment by sheyd** [comment] 2016-10-03 20:40
Subscription numbers finally up to date. Working on unsubscribe numbers now.

**Comment by jessleenyc** [comment] 2016-10-04 16:24
Since our numbers appear to be higher than the UI now, are we concerned we're overreporting at all?

**Comment by sheyd** [comment] 2016-10-07 13:57
@jessleenyc No, confirmed that things are accurate. In other news, unsubscribe numbers are up to date now as well!

**Closed by sheyd** 2016-10-07 13:57 UTC
Labels: BLOCKER
