### ISSUE TITLE
Backfill Historical Northstar Records to Update Last_Accessed / Logged_in

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#374] opened 2017-06-27 19:29 UTC
_TASK_
-------------------
#### Description
As a Data Analyst I want all updated records from Northstar in the Quasar.Users table so that I can see the most up-to-date user info and the most recent time all users have accessed the site. 

#### Why This is Important
Backfilling all Northstar records is necessary so that we have the most up-to-date user information for all user in Quasar.

#### Definition of Done
**Given** Sena completes the backfill of Northstar historical records
**When** James queries the quasar users table 
**Then**  He should see updated records from early April 2017, when we started to collect data in Northstar. 

#### Additional Information
- Currently, we ingest user information when a user creates an account. However, we do not ingest user information from Northstar when they update their profile. To be fixed in #373. 

- Ask Dave if we did a bulk migration of last_accessed info from phoenix db into Northstar.

**Comment by DFurnes** [comment] 2017-06-27 19:32
> Ask Dave if we did a bulk migration of last_accessed info from phoenix db into Northstar.

We did not.

**Comment by sheyd** [comment] 2017-06-27 19:43
Backfill kicked off. Will update when it's done.

**Comment by jamjensen** [comment] 2017-06-27 23:09
@sheyd can you include a link to the backfill? I can't find in among the Jenkins jobs. 

I've also noticed that there are 300k (and counting) fewer users with `customer_io_subscription_status` as subscribed since I last checked this morning. Can you please see if the backfill is overwriting subscriptions statuses, and if so, pause it?

**Comment by jamjensen** [comment] 2017-06-28 19:57
**Update** 
While backfilling Northstar records to the Quasar Users table we accidentally set c.io subscription status values to NULL. Documented here -- https://dosomething.slack.com/archives/C0FP51V2T/p1498616931083803 

@sheyd can you provide an update of where we are with updating all users c.io subscription status in the users table based off of the latest c.io export?

**Comment by sheyd** [comment] 2017-06-28 20:09
@jamjensen I've confirmed CSV numbers match up with c.io web numbers. I've imported the CSV into `c_io_export_fix_missing` table, and am doing some data validation. I'm not worried too much about the sub/unsub status updates, but a lot of the sub/unsub times are epoch 00:00:00 times. Looking into why this is.

**Comment by sheyd** [comment] 2017-06-28 22:02
@jamjensen Confirmed that there's only 175,556 email addresses both in CSV export as well in the c.io Web UI that have a . Didn't catch this before, but looks like we didn't have a whole lot of subscribe times in c.io to begin with, and need to re-fill the times from the Mailchimp sub archive tables. 

Based on our IRL conversation, I'm going to get the sub status and whatever dates are in the c.io export propagated back into the `users` table, and we'll punt on the missing sub times till we need them, since we have the old raw data in MailChimp archive tables, and are not currently running an dashboards or analytics on sub times.

**Comment by sheyd** [comment] 2017-06-29 01:53
The backfill is done. @jamjensen Do you want to track the 40K excess users (confirmed they still exist) in this ticket or another one?

**Comment by sheyd** [comment] 2017-06-29 15:45
I've merged the code to make the updated non-destructive to Northstar records and backfill all `last_accessed` and `last_logged_in` records. 

I've also kicked off a full backfill from the beginning.

**Comment by sheyd** [comment] 2017-07-05 11:07
This is complete after 57 hours. Interesting to note, there were some more API failure this time around than not from Northstar than last time.

There are a total of 132,419 records with either last_logged_in, last_accessed or both in the `users` table, via:
```
SELECT northstar_id, last_logged_in, last_accessed FROM users
WHERE last_logged_in IS NOT NULL OR last_accessed IS NOT NULL;
```

The earliest `last_logged_in` is 2017-02-27 16:10:41, and the earliest `last_accessed` is 2017-06-07 21:00:05. Closing ticket.

**Closed by sheyd** 2017-07-05 11:07 UTC
