### ISSUE TITLE
Backfill all Rogue data in the Campaign Activity Table

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#298] opened 2017-02-10 18:02 UTC
_TASK_
-------------------
#### Description
Begin backfilling Rogue data into the Quasar `Campaign_Activity` table so that we're not longer reliant on phoenix for user activity. 

#### Why This Matters/Use Case Example
We need to have all user activity data in Quasar before Rogue can go live. Once Rogue goes live it will no longer be posting to Phoenix Ashes.

**Comment by jamjensen** [comment] 2017-06-19 18:50
**To track progress of the backfill:** https://docs.google.com/a/dosomething.org/spreadsheets/d/14Emfai_I6WQj4PpMGG3x5Nq7beMjh9kl6KUNkbg00Gc/edit?usp=sharing

**Comment by sheyd** [comment] 2017-06-26 14:48
I added primary key per #365, and have restarted a backfill as of 3PM EST on 6/25/17. We're about halfway through the records in 19 hours or so.

**Comment by sheyd** [comment] 2017-06-28 13:34
@jamjensen Backfill finished. I'm going to actually assign this ticket to you since backfill is complete.

**Comment by jamjensen** [comment] 2017-06-28 22:55
Confirming that the exact same number of distinct signup ids (3,407,695) exists in both the Rogue_prod signup table and the Quasar campaign_activity table.

**Comment by jamjensen** [comment] 2017-06-28 23:06
Number of distinct post ids in rogue prod: 271,630
Number of distinct post ids in quasar: 270,992

Queries: 
`select count(distinct post_id)
from quasar.campaign_activity`

`select count(distinct post_id)
from quasar.campaign_activity`

**Comment by jamjensen** [comment] 2017-07-14 14:45
As of July 14th, the timestamp of the most recent record we have in the `campaign_activity` table is 2017-06-06 21:07:21. 

Rogue ran the Keeper Upper yesterday afternoon, so I just kicked off the Campaign Activity Backfill Diff to import new records from Rogue prod into Quasar. And I set the job to go get records created in the past 914 hours.

**Comment by jamjensen** [comment] 2017-07-17 17:35
@sheyd On Friday afternoon the Campaign Activity Backfill Diff completed after running for nearly 2 hours.  

The `campaign_activity` table shows increases in the total number of records and number of distinct `signup_ids` -- but I'm still seeing the same number of `post_ids` (270,992) And the most recent timestamp for `submission_created_at` is 2017-06-07 02:19:45. 

I asked Furnes to query rogue prod for total number of distinct post ids and he told me - 297,522.

**Comment by sheyd** [comment] 2017-07-17 18:11
That's disturbing. Taking a look now.

**Comment by sheyd** [comment] 2017-07-17 18:22
@jamjensen I don't have a good explanation. I've kicked off another 60 day backfill to see if corrects the issue, and will track down further if that doesn't do the trick.

I verified data is updated from the Rogue API, and the job didn't hit any snags or MySQL errors.

**Comment by sheyd** [comment] 2017-07-18 13:25
@jamjensen The number now is up to 296,813 in Quasar. I'm kicking off a 48 hour backfill to see if that makes up for the ~700 diff.

**Comment by sheyd** [comment] 2017-07-19 14:53
Running another backfill diff IRL with @jamjensen. Ref numbers before run:
Rogue Prod: `298227`
Quasar: `296813`

**Comment by sheyd** [comment] 2017-07-19 15:03
Post Backfill:
Rogue Prod: `298227`
Quasar: `297518`

That ~700 number seems to point to something in the script, like it's not getting the last page of results or something. I'll file a ticket for that, but I don't think this should be an imminent blocker. 

Also confirmed we have records from 7-19 in the `campaign_activity` table.

**Comment by jamjensen** [comment] 2017-07-20 14:57
Jenkins Backfill Diff finished at 10:52am on 7/20: 
Rogue Prod: `298,681` 
Quasar: `297,971`
Diff: 710

**Closed** 2017-07-26 17:23 UTC
